# Copyright (C) 2019 Skale-5 <ops@skale-5.com>
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: 4
    requests.cpu: 500m
    requests.memory: 100Mib
    limits.cpu: 1000m
    limits.memory: 750Mib
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resources
spec:
  hard:
    persistentvolumeclaims: 200
    requests.storage: 500Gi
    zonal-pd-ssd.storageclass.storage.k8s.io/requests.storage: 500Gi
